### ISSUE TITLE
Création roadmap cineHub

### ISSUE THREAD

**Issue by lokkotara** [CineCare/cineHub-frontend#1]
Elle doit reprendre les étapes clés du projet en tenant compte des différentes échéances à présenter.

14 Nov = 
20 Dec =

**Comment by Cinecare6** [comment]
Peut-on preciser les dates dans le descriptif ?

**Comment by Cinecare6** [comment]
Tu es vraiment doué dans ce que tu fais c’est tellement satisfaisant à
observer 🤗

Merci mentor doudou
